/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head'
import Image from 'next/image'
import Post from '../components/Post'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'
import { Loader } from '../components/global'

export default function Home() {
  const [posts, setPosts] = useState([])

  const fetchPosts = async () => {
    const res = await fetch('')
    const data = await res.json()
    setPosts(data)
    console.log(data);
  }
  useEffect(() => {
    fetchPosts()
  } , [])

  const postsTemp = [
    {
      post: {
        like: true,
        nblike: 1521,
        description: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        timestamp: 1659725905,
        images: [
          'https://cdn.pixabay.com/photo/2018/09/14/23/28/avatar-3678347_960_720.png',
        ]
      },
      user: {
        avatar: 'https://e7.pngegg.com/pngimages/84/165/png-clipart-united-states-avatar-organization-information-user-avatar-service-computer-wallpaper-thumbnail.png',
        username: 'John Doe',
      },
    },
    {
      post: {
        like: true,
        nblike: 1521,
        description: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        timestamp: 1659725905,
        images: [
          'https://cdn.pixabay.com/photo/2018/09/14/23/28/avatar-3678347_960_720.png',
        ]
      },
      user: {
        avatar: 'https://e7.pngegg.com/pngimages/84/165/png-clipart-united-states-avatar-organization-information-user-avatar-service-computer-wallpaper-thumbnail.png',
        username: 'John Doe',
      },
    }
  ]

  return (
    <div className={styles.container}>
      <Head>
        <title>Festiv'App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {posts.length == 0 && // if posts is empty, we display the loading animation
          <Loader />
        }
        {posts.map((post, index) => <Post key={index} user={post.user} post={post.post}/>)}
      </main>
    </div>
  )
}
